### ISSUE TITLE
“Middle click to open in new tab” broken

### ISSUE THREAD

**Issue by notpushkin** [MoOx/moox#77]
It's a common gesture that some people (including me) are still using today – at least those who have middle button :) However, when I middle-click a link on moox.io, it either opens in current tab or opens _both_ in current and a new tab. I'd be happy to send a PR but I'm not yet sure where to look at because I'm not familiar with the react-native-web stack. Bottom line is, a click handler for links should handle only left button (`e.which == 1 || e.button == 0`) and ignore the event otherwise.

**Comment by MoOx** [comment]
@notpushkin thanks for reporting. I will update my site for another engine (nextjs probably) soon, that should handle the issue (finger crossed).
I could patch my current engine but I am too lazy to be honest 😂

**Comment by MoOx** [comment]
Fixed !
